---
title: "Corrigido Final"
author: "Vera Pinto & Carina Silva"
date: "2023-01-10"
output: html_document
---

```{r setup, echo=FALSE}
library(readxl)
NGS_Farmacogenetica_completa_original <- read_excel("clean.xlsx", sheet="clean")
data2<-as.data.frame(NGS_Farmacogenetica_completa_original)
names(data2)
class(data2)
attach(data2)
```

```{r,echo=FALSE}
library(dplyr)
amostra.unicas<-data2 %>% distinct(data2$Sample, .keep=data2$Variant)
str(amostra.unicas)
dim(amostra.unicas)
amostra.unicas<-as.data.frame(amostra.unicas)
                      

coordenadas.unicas<-data2 %>% distinct(data2$Coordinate, .keep=data2$Chr)
names(coordenadas.unicas)
dim(coordenadas.unicas)
class(coordenadas.unicas)

classification.unicas<-data2 %>% distinct(data2$Classification, .keep=data2$Sample)
names(classification.unicas)
table(classification.unicas$`data2$Classification`)
class(classification.unicas)
dim(classification.unicas)

snp.unicas<-data2 %>% distinct(data2$SNP, .keep=data2$Coordinate)
names(snp.unicas)
table(snp.unicas$`data2$SNP`)
class(snp.unicas)
dim(snp.unicas)

gen.unicas<-data2 %>% distinct(data2$Genotype, .keep=data2$Sample)
names(gen.unicas)
table(gen.unicas$`data2$Genotype`)
class(gen.unicas)
dim(gen.unicas)

rec.unicas<-data2 %>% distinct(data2$Recess, .keep=data2$Sample)
names(rec.unicas)
table(rec.unicas$`data2$Recess`)
class(rec.unicas)
dim(rec.unicas)

snpid.unicas<-data2 %>% distinct(data2$SNPID, .keep=data2$Coordinate)
names(snpid.unicas)
table(snpid.unicas$`data2$SNPID`)
class(snpid.unicas)
dim(snpid.unicas)

coordenada_lista_amostras2<-function(coordenadas.unicas,amostra.unicas,data2) {
  
  linhas_novas<-data.frame(matrix(ncol =9, nrow = 0))
  data_final<-data.frame(matrix(ncol = 9, nrow = 0))
  

  
  for (i in 1:dim(coordenadas.unicas)[1]){
   
 # identifica as amostras associadas a uma coordenada
    lista_samples<-as.data.frame(data2$Sample[data2$Coordinate==coordenadas.unicas[i,1]])
    
    #conjunto de amostras que não estão associadas a uma coordenada
    out<-setdiff(amostra.unicas[,1],lista_samples[,1])
    
        if (length(out)!=0){
          
          classif<-data2[data2$Sample %in% out,]
          classif2<-classif %>% distinct(classif$Sample, .keep=classif$Classification)
          classif2<-as.data.frame(classif2)
          snp<-data2[data2$Sample %in% out,]
          snp2<-snp %>% distinct(snp$Sample, .keep=snp$SNP)
          snp2<-as.data.frame(snp2)
          gen<-data2[data2$Sample %in% out,]
          gen2<-gen %>% distinct(gen$Sample, .keep=gen$Genotype)
          gen2<-as.data.frame(gen2)
          rec<-data2[data2$Sample %in% out,]
          rec2<-rec %>% distinct(rec$Sample, .keep=gen$Recess)
          rec2<-as.data.frame(rec2)
          snpid<-data2[data2$Sample %in% out,]
          snpid2<-snp %>% distinct(snpid$Sample, .keep=snp$SNPID)
          snpid2<-as.data.frame(snpid2)
          linhas_novas<-data.frame(Sample=out,Chr=rep(coordenadas.unicas[i,2],length(out)),Coordinate=rep(coordenadas.unicas[i,1],length(out)),
                                     Classification=classif2[,2],Variant=rep(0,length(out)), SNP=rep(snp.unicas[i,1],length(out)), Genotype="hom",Recess=0,SNPID=rep(snpid.unicas[i,1],length(out)))
    
          data_final<-rbind(data_final,linhas_novas)
          
                            } 
    
    else i<-i+1
    
  } 
  data_final <- data_final %>% distinct()
  return(data_final)
}


LISTA2<-coordenada_lista_amostras2(coordenadas.unicas,amostra.unicas,data2)


#juntar LISTA com Dados

FINAL2<-rbind(data2,LISTA2)
dim(FINAL2)
```

```{r,echo=FALSE}
results2<-data.frame(matrix(ncol = 5, nrow = 0)) #data frame final
  cols <- (c("Chr", "SNP","Coordinate","SNPID","p-value"))
  colnames(results2) <- cols
  

  for (i in 1:23){
    if (i==21){next}
    sub <- subset(FINAL2, Chr==i)
    coor.unic<-sub %>% distinct(sub$Coordinate)
              for (j in  1:nrow(coor.unic)) {
                      coor<-coor.unic$`sub$Coordinate`[j]
                      sub2 <- subset(sub, Coordinate==coor)
                      SNP<-sub2$SNP[1]
                      SNPID<-sub2$SNPID[1]
                      t<-table(sub2$Variant,sub2$Classification)
      
                          if (dim(t)[1]==2 & dim(t)[2]==2){
         
                            x<-fisher.test(t)
                            v<-x$p.value
                            v1<-data.frame(t(matrix(c(sub$Chr[i],SNP,coor,SNPID,v))))
                            colnames(v1) <- cols
                            results2<-rbind(results2,v1)
                                         }
      
        
            }
     
    
    }
```

```{r,echo=FALSE}
results2
```
```{r,echo=FALSE}
x<-p.adjust(results2$`p-value`, method = "holm", n=length(results2$`p-value`))
```

```{r}
y<-p.adjust(results2$`p-value`, method = "fdr", n=length(results2$`p-value`));y

```

```{r}
library(qqman)

results2$Chr<- as.numeric(results2$Chr)
results2$Coordinate<- as.numeric(results2$Coordinate)
results2$`p-value`<- as.numeric(results2$`p-value`)
attach(sem_recessividade)


manhattan(results2, chr = "Chr", bp="Coordinate", p="p-value", snp = "SNP",suggestiveline=1.3, logp=T, annotatePval = 0.05 )

```

```{r, echo=FALSE}
results3<-data.frame(matrix(ncol = 5, nrow = 0)) #data frame final
  cols <- (c("Chr", "SNP","Coordinate","SNPID","p-value"))
  colnames(results3) <- cols
  

  for (i in 1:23){
    if (i==21){next}
    sub <- subset(FINAL2, Chr==i)
    coor.unic<-sub %>% distinct(sub$Coordinate)
              for (j in  1:nrow(coor.unic)) {
                      coor<-coor.unic$`sub$Coordinate`[j]
                      sub2 <- subset(sub, Coordinate==coor)
                      SNP<-sub2$SNP[1]
                      SNPID<-sub2$SNPID[1]
                      t<-table(sub2$Recess,sub2$Classification)
      
                          if (dim(t)[1]==2 & dim(t)[2]==2){
         
                            x<-fisher.test(t)
                            v<-x$p.value
                            v1<-data.frame(t(matrix(c(sub$Chr[i],SNP,coor,SNPID,v))))
                            colnames(v1) <- cols
                            results3<-rbind(results3,v1)
                                         }
      
        
            }
     
    
    }
```

```{r, echo=FALSE}

results3

```

```{r, echo=FALSE}
w<-p.adjust(results3$`p-value`, method = "holm")
```

```{r}
z<-p.adjust(results3$`p-value`, method = "fdr", n=length(results3$`p-value`))
```

```{r}

results3$Chr<- as.numeric(results3$Chr)
results3$Coordinate<- as.numeric(results3$Coordinate)
results3$`p-value`<- as.numeric(results3$`p-value`)

manhattan(results3, chr = "Chr", bp="Coordinate", p="p-value", snp = "SNP",suggestiveline=1.3, logp=T, annotatePval = 0.05)
```